modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="free_my_hotbar"
version="${version}"
displayName="Free My Hotbar"
description="A Minecraft mod."
authors="Your Name"

[[dependencies."free_my_hotbar"]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies."free_my_hotbar"]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"
