modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="free_my_hotbar"
version="${version}"
displayName="Free My Hotbar"
description="A Minecraft mod."
authors="Your Name"

[[mixins]]
config="free-my-hotbar.mixins.json"

[[mixins]]
config="free-my-hotbar.client.mixins.json"

[[dependencies."free_my_hotbar"]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies."free_my_hotbar"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"
